### ISSUE TITLE
mp_firingrange Bad...

### ISSUE THREAD

**Issue by megvadulthangya** [ineedbots/iw4x_waypoints#4]
Dont matter if i use GSC format, or i remove from the _bot_utility.gsc 

Then delete from waypoint gsc 

And then use the  csv format

Allways gives

script runtime warning: potential infinite loop in script 5000 > 5000

And crash the server making 300+mb logfile...

**Comment by ineedbots** [comment]
https://github.com/ineedbots/iw4x_bot_warfare/issues/33
